runtime: aspnetcore
env: flex
beta_settings:
    cloud_sql_instances: "youtapia-6ea8d:us-east1:mysql-youtapia=tcp:3306"
env_variables:
    AppSettings__MySqlConnectionString: "Host=cloudsql;Uid=pransdell;Pwd=password1;Database=youtapia_schema;"

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10