runtime: aspnetcore
env: flex
beta_settings:
    cloud_sql_instances: "hackathon-ascendum:us-east1:hackathon=tcp:3306"
env_variables:
    AppSettings__ConnectionString: "Host=cloudsql;Uid=pransdell;Pwd=password1;Database=hackathon_schema;"

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10