DROP TABLE IF EXISTS Organization;


DROP TABLE IF EXISTS AdminUser;

CREATE TABLE AdminUser (
  Id CHAR(38) NOT NULL,
  Email VARCHAR(35) NOT NULL,
  PasswordHash VARBINARY(64) NOT NULL,
  Salt VARCHAR(38) NOT NULL,
  CreatedDate DATETIME DEFAULT CURRENT_TIMESTAMP,
  ActivatedDate DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (Id),
  UNIQUE KEY(Email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS Message;
    
CREATE TABLE Message (
  Id INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(250) NOT NULL,
  PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS GameUser;

CREATE TABLE GameUser (
  Id CHAR(38) NOT NULL,
  Name VARCHAR(35) NOT NULL,
  CreatedDate DATETIME DEFAULT CURRENT_TIMESTAMP,
  Active INT NOT NULL DEFAULT 1,
  PRIMARY KEY (Id),
  UNIQUE KEY(Name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS BaseballGame;

CREATE TABLE BaseballGame (
  Id INT NOT NULL AUTO_INCREMENT,
  HomeTeam VARCHAR(250) NOT NULL,
  HomeTeamLogo VARCHAR(250) NOT NULL,
  HomeTeamRuns INT NULL,
  AwayTeam VARCHAR(250) NOT NULL,
  AwayTeamLogo VARCHAR(250) NOT NULL,
  AwayTeamRuns INT NULL,
  StartDate DateTime NOT NULL,
  Status VARCHAR(250) NOT NULL,
  Inning INT NULL,
  InningHalf VARCHAR(10) NULL,
  ExternalGameId INT NULL,
  PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS MoundGame;

CREATE TABLE MoundGame (
  Id INT NOT NULL AUTO_INCREMENT,
  Status VARCHAR(250) NOT NULL,
  BaseballGameId INT NOT NULL,
  PRIMARY KEY (Id),
  CONSTRAINT FK_MoundGame_BaseballGame FOREIGN KEY (BaseballGameId) REFERENCES BaseballGame(Id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS MoundResult;

CREATE TABLE MoundResult (
  Id INT NOT NULL AUTO_INCREMENT,
  MoundResult VARCHAR(250) NULL,
  Status VARCHAR(250) NOT NULL,
  MoundGameId INT NOT NULL,
  CreatedDate DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (Id),
  CONSTRAINT FK_MoundResult_MoundGame FOREIGN KEY (MoundGameId) REFERENCES MoundGame(Id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS UserMoundResult;

CREATE TABLE UserMoundResult (
  Id INT NOT NULL AUTO_INCREMENT,
  Submission VARCHAR(250) NOT NULL,
  GameUserId CHAR(38) NOT NULL,
  MoundResultId INT NOT NULL,
  CreatedDate DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (Id),
  UNIQUE KEY (GameUserId, MoundResultId),
  CONSTRAINT FK_UserMoundResult_GameUser FOREIGN KEY (GameUserId) REFERENCES GameUser(Id) ON DELETE CASCADE,
  CONSTRAINT FK_UserMoundResult_MoundResult FOREIGN KEY (MoundResultId) REFERENCES MoundResult(Id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



INSERT INTO Message (Name) VALUES ('Let\'s Get Hacking!');