DROP TABLE IF EXISTS Organization;


DROP TABLE IF EXISTS AdminUser;

CREATE TABLE AdminUser (
  Id CHAR(38) NOT NULL,
  Email VARCHAR(35) NOT NULL,
  PasswordHash VARBINARY(64) NOT NULL,
  Salt VARCHAR(38) NOT NULL,
  CreatedDate DATETIME DEFAULT CURRENT_TIMESTAMP,
  ActivatedDate DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (Id),
  UNIQUE KEY(Email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS Message;
    
CREATE TABLE Message (
  Id INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(250) NOT NULL,
  PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO Message (Name) VALUES ('Let\'s Get Hacking!');